name = "test"
root = "~/"

[[window]]
name = "editor"
layout = "main-vertical"

  [[window.pane]]
  commands = ["vim"]

  [[window.pane]]
  commands = ["guard"]

[[window]]
name = "server"
commands = ["bundle exec rails s"]

[[window]]
name = "logs"
commands = ["tail -f log/development.log"]
