version: 2

defaults: &defaults
  docker:
    - image: circleci/golang:1.11.4
  environment:
    GOPATH: /go

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: make dependencies
      - run:
          name: Run tests
          command: make test
      - run:
          name: Upload to Codecov.io
          command: bash <(curl -s https://codecov.io/bash)
      - run: OSES="darwin linux" make build
      - store_artifacts:
          path: bin
  release:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Release version
          command: |
            export GITHUB_TAG=$CIRCLE_TAG
            export GITHUB_REPONAME=$CIRCLE_PROJECT_REPONAME
            export GITHUB_USERNAME=$CIRCLE_PROJECT_USERNAME
            make release

workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

