name: CI

on:
  push:
    branches: [ main ]
    tags:
      - v*
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OSES: "darwin linux"

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2-beta
      with:
        go-version: 1.14.2
    - run: make dependencies
    - name: Run tests
      run: make test
    - uses: codecov/codecov-action@v1
    - name: Build
      run: make build
    - name: Release a version
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        go get github.com/tcnksm/ghr
        export GITHUB_TAG=`echo $GITHUB_REF | sed "s|refs/tags/||"`
        export GITHUB_REPONAME=`echo $GITHUB_REPOSITORY | cut -d '/' -f 2`
        export GITHUB_USERNAME=`echo $GITHUB_REPOSITORY | cut -d '/' -f 1`
        export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
        make release

